// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	// The ID of the user
	ID string `json:"id"`
	// The user's first name
	FirstName string `json:"firstName"`
	// The user's last name
	LastName string `json:"lastName"`
}
