package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"time"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/sop/auth"
	errs "git.las.iastate.edu/SeniorDesignComS/2023spr/sop/errors"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/sop/graph/generated"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (bool, error) {
	user := auth.GetUserFromContext(ctx)
	if user != nil {
		return false, errs.NewForbiddenError(ctx, "You are already logged in.")
	}

	userId, err := r.UserService.ValidateLogin(ctx, username, password)
	if err != nil {
		return false, err
	}

	expires := time.Now().Add(time.Hour * 24 * 30)

	token, err := r.UserService.CreateUserSession(ctx, *userId, expires)
	if err != nil {
		return false, err
	}

	request := auth.GetRequestFromContext(ctx)
	request.SetAuthToken(*token, expires)

	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	user := auth.GetUserFromContext(ctx)
	if user == nil {
		return true, nil
	}

	err := r.UserService.DeleteUserSessions(ctx, user.ID)
	if err != nil {
		return false, err
	}

	request := auth.GetRequestFromContext(ctx)
	request.ClearAuthToken()

	return true, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
